# Change the look of Adwaita, with ease
# Copyright (C) 2022 Gradience Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          dnf -y install docker
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          repository-name: gnome-nightly
          bundle: gradience-devel.flatpak
          manifest-path: build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}

on:
  pull_request:
  schedule:
    - cron:  '0 0,12 * * *'
  workflow_dispatch:

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for typos
      - uses: crate-ci/typos@master
        with:
          config: ./typos.toml

  dependency-review:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: Dependency review
        uses: actions/dependency-review-action@v3

  translation:
    name: Generate .pot
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3

      - name: Update .pot
        uses: GradienceTeam/action-update-pot@main
        with:
          title: "Gradience POT file"
          copyright: "Gradience Team"
          license: "GNU GPLv3"
          author: "Gradience Team"
          commiter: "Gradience Bot"
          commiter_email: "AdwCustomizerTeam@proton.me"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on: [pull_request_target, issues]

jobs:
  greeting:
    name: Greetings
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room https://matrix.to/#/#Gradience-space:envs.net or the discord server https://discord.com/invite/4njFDtfGEZ"
        pr-message: "Welcome on Gradience. 🥳 We really appreciate your pull request. The core team will review your issue as soon as possible. You can also join the matrix room https://matrix.to/#/#Gradience-space:envs.net or the discord server https://discord.com/invite/4njFDtfGEZ."
