# Change the look of Adwaita, with ease
# Copyright (C) 2022 Gradience Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check for typos
      uses: crate-ci/typos@master

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.

        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines.
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  pypi-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run a multi-line script
        run: |
          curl -O https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/pip/flatpak-pip-generator
          chmod +x flatpak-pip-generator
          python -m pip install requirements-parser
          ./flatpak-pip-generator --requirements-file=requirements.txt --output pypi-dependencies
          mv pypi-dependencies.json build-aux/flatpak/pypi-dependencies.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "ci: update Flatpak pypi dependencies"
          title: Update `pypi-dependencies.json`
          body: This is an auto-generated PR with the generation of `pypi-dependencies.json`.
          labels: flatpak, automated pr
          committer: "AdwCustomizer <AdwCustomizerTeam@proton.me>"
          author: "AdwCustomizer <AdwCustomizerTeam@proton.me>"
          branch: pypi-deps

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: arm64
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
      with:
        repository-name: gnome-nightly
        bundle: gradience-devel.flatpak
        manifest-path: build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
