name: Sphinx build

on: push

jobs:
  build-i18n:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [fr, ru]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: GradienceTeam/sphinx-publish-action@master
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          target_branch: 'gh-pages'
          target_path: '{{ matrix.lang }}'
  build-en:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: GradienceTeam/sphinx-publish-action@master
      with:
          token: ${{ secrets.ACCESS_TOKEN }}
          target_branch: 'gh-pages'