on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Checkout
          uses: actions/checkout@v3.0.2
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: palette.flatpak
          manifest-path: com.github.AdwCustomizerTeam.AdwCustomizer.yml
          cache-key: flatpak-builder-${{ github.sha }}