name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        issue-message: "Welcome on Adwaita Manager. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible."
        pr-message: "Welcome on Adwaita Manager. 🥳 We really appreciate your pull request. The core team will review your issue as soon as possible.""
