name: "Translation - LINGUAS"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 6 * * 5'

jobs:
  update-pot:
    name: Update .pot
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Update linguas
        uses: AdwCustomizerTeam/action-update-linguas@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
