name: Build meson
on:
  push:
    branches: [main, next]
  pull_request:
jobs:
  meson:
    name: "Meson"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: -Db_coverage=true
          options: --verbose
          meson-version: 0.53.2
          ninja-version: 1.9.0.post1
          gcovr-version: 4.2