name: Build meson
on:
  push:
    branches: [main, next]
  pull_request:
jobs:
  meson:
    name: "Meson"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          options: --verbose
