name: "Translation"

on:
  pull_request:
    branches: [ "main" [
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  generate:
    name: Generate .pot and LINGUAS 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update .pot
        uses: AdwCustomizerTeam/action-update-pot@main
        with:
          title: "Adwaita Manager POT file"
          copyright: "Adwaita Manager Team"
          license: "GNU GPLv3"
          author: "Adwaita Manager Team"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Update linguas
        uses: AdwCustomizerTeam/action-update-linguas@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
   
